# default profile
profile = 'test'

model = 'gpt-5-codex'
model_provider = 'openai'
approval_policy = 'never'
disable_response_storage = true

[model_providers.openai]
name = 'OpenAI'
base_url = 'https://api.openai.com/v1'
env_key = 'OPENAI_API_KEY'
wire_api = 'chat'

[profiles.test]
model = 'gpt-5-codex'
model_provider = 'openai'
approval_policy = 'never'
disable_response_storage = true
reasoning_effort='high'

